version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: sui-middleware-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: